### ISSUE TITLE
Tests are not Windows friendly

### ISSUE THREAD

**Issue by henrikac** [charmbracelet/taskcli#2]
I can see this is fixed in #1. See this issue as a tip for future code :)

Instead of checking path separators like `== '/'` a better approach is to use [os](https://pkg.go.dev/os).[PathSeparator](https://pkg.go.dev/os#PathSeparator). Otherwise this check would fail on Windows.

https://github.com/charmbracelet/taskcli/blob/23d7ac29a6919eaaf563b7819ac5ae82fad97e6d/db_test.go#L206C2-L208C3

**Comment by caarlos0** [comment]
yep, this should be fixed now!
thanks @henrikac :)
