### ISSUE TITLE
LICENSE not specified

### ISSUE THREAD

**Issue by czonios** [charmbracelet/taskcli#3]
Hello,

I have built a project based on the code in this repository, with additional functionality.
However, I cannot publish it as there is no LICENSE file, which means that this repository and the code are subject to copyright laws, with all rights reserved by the authors.

If you intend to allow this project to be used by others, it would be nice to choose an open source license (such as MIT). Since this is a repo showcasing your other projects (bubbletea, bubbles, lipgloss etc.) I imagine this is not a problem.

Thank you for the consideration and the awesome software!

**Comment by bashbunni** [comment]
Hey @czonios sorry for the delay on this one. Just added an MIT license to the project. Thanks for the support, would love to see what you've built!
