### ISSUE TITLE
refactor: use lipgloss table as renderer instead of table bubble

### ISSUE THREAD

**Issue by bashbunni** [charmbracelet/taskcli#4]
https://github.com/charmbracelet/lipgloss/blob/master/table/table.go

**Comment by MovieMaker93** [comment]
Hi @bashbunni , 
Are you looking for contributors?
If yes, I would like to help. Would be better add a package only for the style (called like "UI")?
And Why are you changing to the lipgloss table over the bubble one? Is it better?
